---
title: "STAT 421 HW 10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part a)

```{r}
rateParam = 1/5

time <- 0
arrivalTimes <- NULL  #not the most efficient way to do this in terms of memory
while(time < 100)
{
	waitTime <- rexp(1, rate = rateParam)
	time <- time + waitTime
	arrivalTimes <- c(arrivalTimes, time)
}

#plot(arrivalTimes, seq(1, length(arrivalTimes)), type = 's')


```

## Part b)

The distribution of the number of arrivals should be a Poisson(20).

## Part c)

```{r}
rateParam = 1/5

trials <- list()

for(i in 1:100){
  
  arrivalTimes <- NULL  #not the most efficient way to do this in terms of memory
  time <- 0
  
  while(time < 100)
  {
	  waitTime <- rexp(1, rate = rateParam)
	  time <- time + waitTime
	  arrivalTimes <- c(arrivalTimes, time)
  }
  arrivalTimes
  trials[[i]] <- arrivalTimes
}


```


```{r}

numtrials <- numeric()

for(i in 1:length(trials)){
  numtrials[i] <- length(trials[[i]]) 
}

hist(numtrials, freq = F,col="grey")
xlines <-seq(0,100,length.out=100) #seq of x for pdf
lines(x = xlines,y=dpois(round(xlines),rateParam*100))

```


## Part d)

```{r}

num0to50 <- numeric()
num50to100 <- numeric()


for (i in 1:length(trials)){
  
  xvec <- trials[[i]]
  xsum <- sum(xvec<=50)
  num0to50[i] <- xsum
}

for (i in 1:length(trials)){
  
  xvec <- trials[[i]]
  xsum <- sum(xvec>50)-1
  num50to100[i] <- xsum
}


hist(num0to50, freq = F)
xlines <-seq(0,50,length.out=50) #seq of x for pdf
lines(x = xlines,y=dpois(round(xlines),rateParam*50))


hist(num50to100, freq = F)
xlines <-seq(0,50,length.out=50) #seq of x for pdf
lines(x = xlines,y=dpois(round(xlines),rateParam*50))


```

The distributions should be the same.



## Part e)

```{r}

rateParam = 1/5

timetrials <- numeric()

for(i in 1:100){
  
  arrivalTimes <- NULL  #not the most efficient way to do this in terms of memory
  time <- 0
  j<-1
  
  while(j < 20)
  {
	  waitTime <- rexp(1, rate = rateParam)
	  time <- time + waitTime
	  arrivalTimes <- c(arrivalTimes, time)
	  j <- j+1
  }
  timetrials[i] <- time
}


hist(timetrials, freq = F)

```







